name: ShortenGamemode
version: '${project.version}'
main: pl.majlitech.shortengamemode.Main
api-version: '1.13'
commands:
  gm:
    usage: /<command>
    description: Gamemode switcher
  gamemode:
    usage: /<command>
    description: Gamemode switcher